---
version: "3.4"
services:
  shortener-db:
    image: postgres:latest
    container_name: social-credit-bot-db
    environment:
      - POSTGRES_USER=social_credit_bot
      - POSTGRES_PASSWORD=hackme
      - POSTGRES_DB=social_credit_bot_db
    ports:
      - 5432:5432